### ISSUE TITLE
Dataflow progressing slowly, bundles being reprocessed without errors being thrown

### ISSUE THREAD

**Issue by KotaiVictor** [GoogleCloudPlatform/DataflowJavaSDK#100]
We've run into an interesting scenario and cannot explain what the problem might be. 

We're currently running a dataflow in streaming mode that should read a lot of data, group it by a string, do some work and then write it off somewhere.  We're using a GlobalWindow, triggering after first of 20 mins since the first element processed or a certain number of elements in the pane.

After a while the reading off pubsub grinds to a halt and the monitoring doesn't show any progress being done; our counters stop incrementing. 
All of the workers are doing work, our internal logging can confirm that, but they do not seem to be progressing. 

We've noticed that the same bundles are being reprocessed numerous times without any error being thrown in any of the worker logs. 

The worker stdout keeps showing "GetData timed out, retrying" and a "ReportStats timed out, retrying" from time to time; so we're not certain what the problem might be. 

We're not seeing any pushbacks or trashing. The gc/memory usage are within acceptable parameters.

**Comment by davorbonaci** [comment]
Hi Kotai,
Sorry that you are having issues. Would you be able to share the job id with us so we can take a deeper look?

Thanks!

**Comment by KotaiVictor** [comment]
Hello Davor,

The job id for the flow is: 2016-01-22_05_50_09-7884313316983863609

Thanks!

**Comment by bjchambers** [comment]
Hi Kotai,

It looks like the streaming backend may be running out of memory and failing to respond to some requests from the worker.

Can you share more details about your pipeline? How many elements do you expect to be in each pane? How big would you expect that to be?

The most likely problem is that the size of the pane contents is too large.  You could try triggering more, smaller panes and see how that affects things.

**Comment by KotaiVictor** [comment]
Hello Ben,

Your assessment is kind of in line with our guesses, although it might be the number of the panes not the size each individual one. To make stuff progress we ended up bumping the workers up to highmem ones and that fixed the problem. We also bumped the message acknowledgement time from the 10 sec default to the max of 10 minutes, but we're not sure how that affected things. 

A bit of background, we're picking data off a pubsub that has ~1500 elements/s pushed to it. The element size is roughly 2-3kb; we window them, group them, do some processing and write them off. 
Atm we're using 5 n1-highmem-4 workers for this; but the problem seems to happen when the subscription has a lot of undelivered messages. 

We group the elements by ids (roughly 700 different ones). The windowing we use is the first off 20 mins since the processing initial element or 75000 elements per pane. The pane sizes will vary depending on how used the ids are, but the more used ones trigger on the 75000 case.

Initially we were grouping by id + date, but that did not work at all, hence the guess of too many panes. 

While looking at the logs, we didn't see any memory warnings; pushback or trashing. On other pipelines that had memory problems we were seeing both. 
We just saw that bundles were being reprocessed and stuff was not progressing.

An unrelated question. What happens to the windows/panes when you cancel the flow? Do the panes trigger and go through the whole processing pipeline before everything closes down?

Thanks!

**Comment by bjchambers** [comment]
If you're using discarding mode, too many panes should not be a problem. I'm not sure why using "id+date" was running into problems.

Panes that are too large (contain too many elements) are problematic because the system has to buffer all of those elements until the pane gets emitted. We suspect you aren't seeing memory problems in the "worker" logs because the layer that is having issues is the backend which stores all this information. It shows up in the "shuffler" or "shuffler-startup" logs.

If you trigger the panes more often (say every 1000 or 5000 elements) how does it work?

On the unrelated question: When the workflow is cancelled the system shuts down without waiting to trigger any buffered panes. See [Updating a Pipeline](https://cloud.google.com/dataflow/pipelines/updating-a-pipeline) for a way to update a running pipeline without losing the buffered data.

**Comment by KotaiVictor** [comment]
We are discarding fired panes. The problems we've noticed with the "id+date" approach were when we had a several days of undelivered messages. In this case the number of panes would increase  polynomially. Not sure if this should cause problems, seemed so from the tests we ran. 

We've tried triggering frames more frequently, at 10 min intervals or at lower pane counts, and it does solves the issue. The problem we have with this is that every pane triggers, after some processing, a file write; we'd  end up with a lot more files. Ideally we'd like to write less often. 
We're looking into another compaction flow to solve the number of file issues, but that will happen later.

Is there anything we can bump up or use to help? If the buffering happens in the backend, I take throwing more workers at the flow won't solve it... but I might be missing something/misunderstood something.
We're expecting the volumes of data and the used ids to increase. 
The current solution would be to trigger panes more often, keep alerts on the subscription to see if it's progressing and do an update when it's hitting memory issues. 

Yes, we update the flows to preserve the data. Just wanted to clear up the cancelling thing. Thanks!

**Comment by bjchambers** [comment]
Regarding the number of files -- one option would be to output every pane to a separate file, but then combine the files when the window is done (or some other event happens). This would allow you to get data out of the system faster (by putting it in the temporary files) but still have a smaller number of final output files.

More workers may help -- the data is stored per-key and each worker runs the backend holding the data for a specific subset of the key-range. More workers means that the data is spread out across more backend instances. You can also try workers with more memory which might help the backends keep up.

**Comment by KotaiVictor** [comment]
We'll eventually give the first suggestion a try and the second is really good info to know. Thanks!
Tying into the memory issue, is there any way to plug in to the backend running out of memory? Possibly writing a custom trigger to pick up on that and start flushing the panes?

**Comment by bjchambers** [comment]
The issue is that the backend only runs out of memory when the trigger fires and it needs to read data from disk into memory. We are working on making it so the backend won't run out of memory in these conditions -- in the meantime the work-arounds mentioned should help.
