### ISSUE TITLE
Status of `retraction` APIs

### ISSUE THREAD

**Issue by rmadsen** [GoogleCloudPlatform/DataflowJavaSDK#114]
One of the most interesting aspects of the DataFlow API to me is the ability to retract previous results when you get late data. In https://www.oreilly.com/ideas/the-world-beyond-batch-streaming-102 this is described as "still in development for Google Cloud Dataflow at this point"

I'm curious about how far along in development APIs like `accumulatingAndRetractingFiredPanes()` are. Are you able to share any updates on the retraction progress or what the finalized APIs look like? 

Also, I imagine there is going to be some pretty complicated logic if you're retracting numbers based on dynamic windows (like sessions)—is this sort of retraction logic targeted for an initial release?

Thanks!

**Comment by ankurcha** [comment]
Any updates on this?

**Comment by dhalperi** [comment]
Hi Ryan, Ankur,

This is now being tracked for the Apache Beam (incubating) project as [BEAM-91](https://issues.apache.org/jira/browse/BEAM-91).

Thanks
Dan
