### ISSUE TITLE
How pass datetime to DatastoreHelper.makeValue(   ?????   )

### ISSUE THREAD

**Issue by albertog** [GoogleCloudPlatform/DataflowJavaSDK#120]
DateTime dti = new DateTime("2016-02-01T00:00:00.000000");
		DateTime dtf = new DateTime("2016-02-08T23:59:59.999999");
		
		DatastoreV1.Query q = DatastoreV1.Query.newBuilder()
	        .addKind(DatastoreV1.KindExpression.newBuilder().setName("Ma").build())
	        .setFilter(DatastoreHelper.makeFilter(
	        		DatastoreHelper.makeFilter("ud",
	        				DatastoreV1.PropertyFilter.Operator.GREATER_THAN_OR_EQUAL, 
	        				DatastoreHelper.makeValue(   ?????   )
	        				).build(),
	        		DatastoreHelper.makeFilter("ud",
	        				DatastoreV1.PropertyFilter.Operator.LESS_THAN_OR_EQUAL, 
	        				DatastoreHelper.makeValue(   ?????  )
	        				).build()
	              ))        
	        .build();
	  return q;

**Comment by dhalperi** [comment]
Hi Alberto,

Thanks!

The `DatastoreHelper` is actually code from Google Cloud Datastore library, not Dataflow :).

However, I think that [this link](https://cloud.google.com/datastore/docs/concepts/entities#Datastore_Properties_and_value_types) will help:

You will want to use the "protocol buffer" version:

> `timestamp_microseconds_value`: `int64` (since Jan 1 1970)

**Comment by dhalperi** [comment]
to round out the answer: [`1000 * DateTime.getMillis()`](http://joda-time.sourceforge.net/apidocs/org/joda/time/base/BaseDateTime.html#getMillis()) will give a number of microseconds in the right units.

However, this will lose the microsecond precision that Datastore supports, if you have such precision in your underlying data. Java in general does not have good support for sub-millis precision.

I think you could do something using [`java.sql.Timestamp`](https://docs.oracle.com/javase/7/docs/api/java/sql/Timestamp.html#valueOf(java.lang.String)) instead if you want to keep the microsecond precision.

**Comment by dhalperi** [comment]
Finally, I checked with the Datastore team and they pointed me at [`makeValue(Date)`](https://github.com/GoogleCloudPlatform/google-cloud-datastore/blob/24cd676cd91af379a92ad0b27e8f95a4b51d1071/java/datastore/src/main/java/com/google/api/services/datastore/client/DatastoreHelper.java#L410). You'd need to use `DateTime.toDate()` first.

Thanks! Please let me know if there are further issues.
