### ISSUE TITLE
Ran out of memory running WordCount on large file

### ISSUE THREAD

**Issue by psybers** [GoogleCloudPlatform/DataflowJavaSDK#15]
If I run (using DirectPipelineRunner) the WordCount example with an input file of 800mb, the JVM runs out of memory:

[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.1:java (default-cli) on project google-cloud-dataflow-java-examples-all: An exception occured while executing the Java class. null: InvocationTargetException: Java heap space -> [Help 1]

This seems to imply that we can only process input data that is smaller than the heap available to the VM.  Is that correct?  If so, how can this process big data?

**Comment by francesperry** [comment]
The DirectPipelineRunner processes your Dataflow pipeline on a single machine. It's intended for development and unit testing over smaller test data.

When you're ready to scale up to real data sizes, use another runner. This repository includes the DataflowPipelineRunner, which runs your pipeline on the Google Cloud Dataflow Service (now in Beta and publicly available!). There are also third party runners available to run on Spark or Flink.
