### ISSUE TITLE
Mvn Install Tests fail on Mac OSX with non standard Region Preferences

### ISSUE THREAD

**Issue by primedape** [GoogleCloudPlatform/DataflowJavaSDK#17]
When running "mvn clean install" to install DataFlowJavaSDK on a MacBook with OSX Mavericks and non standard settings in the Language and Region Preferences, the installation fails with the following Test Errors:

Failed tests: 
  CombineValuesFnTest.testCombineValuesFnExtract:321 arrays first differed at element [0]; expected:<[ValueInGlobalWindow: KV(a, 4.5)]> but was:<[ValueInGlobalWindow: KV(a, 4,5)]>
  CombineValuesFnTest.testCombineValuesFnAll:240 arrays first differed at element [0]; expected:<[ValueInGlobalWindow: KV(a, 6.0)]> but was:<[ValueInGlobalWindow: KV(a, 6,0)]>
  LoggingMediaHttpUploaderProgressListenerTest.testLoggingProgressAfterSixtySeconds:57 
Argument(s) are different! Wanted:
mockLogger.debug(
    "Uploading: NAME Average Rate: 0.167 MiB/s, Current Rate: 0.167 MiB/s, Total: 10.000 MiB"
);
-> at com.google.cloud.dataflow.sdk.util.gcsio.LoggingMediaHttpUploaderProgressListenerTest.testLoggingProgressAfterSixtySeconds(LoggingMediaHttpUploaderProgressListenerTest.java:57)
Actual invocation has different arguments:
mockLogger.debug(
    "Uploading: NAME Average Rate: 0,167 MiB/s, Current Rate: 0,167 MiB/s, Total: 10,000 MiB"
);
-> at com.google.cloud.dataflow.sdk.util.gcsio.LoggingMediaHttpUploaderProgressListener.progressChanged(LoggingMediaHttpUploaderProgressListener.java:78)

Resetting the Language and Region Settings to Default fixes the problem.

**Comment by davorbonaci** [comment]
Hi Alexander,
Thanks for reporting this. We are aware of this issue and actively working on it. We expect to resolve this quickly. In the meanwhile, I hope it is not a big pain to switch the locale manually.

Thanks!

**Comment by primedape** [comment]
No sweat. Everything is already installed on my side. I only reported the
issue so others have one problem less.

Davor Bonaci <notifications@github.com> schrieb am Do., 23. Apr. 2015 19:01:

**Comment by davorbonaci** [comment]
Hi Alexander,
We have addressed this. Please let us know if you see any additional issues. Thanks!
