### ISSUE TITLE
Expose WindowFn attributes

### ISSUE THREAD

**Issue by mbalassi** [GoogleCloudPlatform/DataflowJavaSDK#18]
Hi,

I'm implementing a PipelineRunner that runs Google Dataflow programs as [Apache Flink](http://flink.apache.org/) [Streaming](http://ci.apache.org/projects/flink/flink-docs-master/apis/streaming_guide.html) jobs.

To translate the windowing functions I need to access the attributes of the specific `WindowFn` subclasses, e.g. [this](https://github.com/GoogleCloudPlatform/DataflowJavaSDK/blob/master/sdk/src/main/java/com/google/cloud/dataflow/sdk/transforms/windowing/FixedWindows.java#L40) one.

Is there a reason for not exposing those?

**Comment by mbalassi** [comment]
The suggested changes are contained in aabd119. I made a pass over the `sdk.transforms.windowing` package and added them, where it made sense. 

I found a slight inconsistency: inner classes of `CalendarWindows` are not declared final, differing from the general solution in the package.

**Comment by bjchambers** [comment]
Hello Marton -- this change seems reasonable -- feel free to submit a pull request.

As an aside, do you have any links to the Flink Streaming PipelineRunner? I'd be interested in taking a look to see how that's implemented.

**Comment by mbalassi** [comment]
Hi Ben,

Thanks for approving the change.

As for having a look at the Flink Streaming PipelineRunner I am happy to share it would you, a pair of insider eyes are always very welcome.

To be honest I am still in the prototyping phase, the first version that is worth to have a look at should be there in a week or so. I'll ping you by then.

Anyway, my work in progress commits for the runner go [here](https://github.com/mbalassi/flink-dataflow), after a bit of cleanup they end up [here](https://github.com/mbalassi/flink-dataflow).

**Comment by bjchambers** [comment]
Thanks! I'd be interested in seeing how our windowing model works in your prototype. In the meantime if you have any concerns about how to translate the Dataflow streaming semantics, please feel free to reach out and ask.
