### ISSUE TITLE
Plans to support Parquet Data format?

### ISSUE THREAD

**Issue by samklr** [GoogleCloudPlatform/DataflowJavaSDK#191]
Hello, this is more of a feature request than a real issue.
But are there any plans to support Parquet. I see that there's already a great support for Avro, and given the popularity of usage of Parquet in other Data Processing engines, it would be nice to have it here too.

Thx.

**Comment by dhalperi** [comment]
Hi Sam,

My understanding is that Parquet has a Hadoop [FileInputFormat](https://github.com/Parquet/parquet-mr/blob/master/parquet-hadoop/src/main/java/parquet/hadoop/ParquetInputFormat.java) reader and thus should work with the contributed [`HadoopFileSource`](https://github.com/apache/incubator-beam/blob/master/contrib/hadoop/src/main/java/com/google/cloud/dataflow/contrib/hadoop/HadoopFileSource.java#L103).

Does that solve your needs?

Thanks,
Dan

**Comment by dhalperi** [comment]
Additional improvements related to Parquet and other components of Hadoop ecosystem interaction are supported well in [Apache Beam](https://beam.apache.org).
