### ISSUE TITLE
BigQueryIO.Read handles TIMESTAMP fields inconsistently between local and cloud

### ISSUE THREAD

**Issue by dragomit** [GoogleCloudPlatform/DataflowJavaSDK#20]
When using BigQueryIO.Read to read TIMESTAMP-typed fields, the results come back differently when running locally and when running in Google cloud:
 * locally the data comes back as string representation of floating point number (number of seconds since Unix Epoch)
 * in the cloud the data comes back as human readable timestamp

For example, I've created a csv file containing following data and loaded that into a table in big query:

$ cat timestamps.csv
1970-01-01 00:00:00.000 UTC
1970-01-01 00:00:00.010 UTC
1970-01-01 00:00:00.100 UTC
2015-04-30 12:34:56.789 UTC

$ bq load dataset.table_name timestamps.csv 'timestamp:timestamp'

Then I created the following trivial dataflow pipeline to read the data from BigQuery and dump it as text file:

```java
public static void main(String[] args) {
      Options options = PipelineOptionsFactory.fromArgs(args).withValidation().as(Options.class);

      Pipeline p = Pipeline.create(options);
      p.apply(BigQueryIO.Read.from(options.getInput()))
              .apply(ParDo.of(new DoFn<TableRow, String>() {
                  private static final long serialVersionUID = 0;
                  @Override
                  public void processElement(ProcessContext c) throws Exception {
                      TableRow row = c.element();
                      String timestamp = (String) row.get("timestamp");
                      c.output(timestamp);
                  }
              }))
              .apply(TextIO.Write.named("myout").to(options.getOutput()));
      p.run();
  }
}
```

When running locally results come back as:
0.0
1.430397296789E9
0.1
0.01

When running in GCP, results come back as:
1970-01-01 00:00:00 UTC
1970-01-01 00:00:00.01 UTC
1970-01-01 00:00:00.1 UTC
2015-04-30 12:34:56.789 UTC

Note also how millisecond field may or may not be present, and number of digits  is variable, all of which makes parsing this data more difficult than it needs to be.

**Comment by davorbonaci** [comment]
Thanks for this report. Sounds like a bug. We are investigating.

**Comment by dragomit** [comment]
I suspect this inconsistency is due to the inconsistent behavior of the BigQuery API itself. When running locally BigQueryIO.Read probably uses [BigQuery.Tabledata.list](https://cloud.google.com/bigquery/docs/reference/v2/tabledata/list) API to get table data as json object, while when running in the cloud it probably inserts an [extract job](https://cloud.google.com/bigquery/docs/reference/v2/jobs#configuration.extract) to extract table into GCS. These two methods format TIMESTAMP-typed fields differently, and that's an unfortunate behavior, but it has been "baked" into the BigQuery API for a long time.

Perhaps BigQueryIO.Read should hide these differences from the user and parse the timestamp string into an instance of org.joda.time.Instant.

**Comment by davorbonaci** [comment]
BigQueryIO behavior should now be consistent.

Please let us know if you see any issues. Thanks!

**Comment by q42jaap** [comment]
Running 0.4.150710, a timestamp field from bigquery still returns a string in DirectPipelineRunner

**Comment by q42jaap** [comment]
We've seen inconsistency with respect to milliseconds in the formatting. Locally we see milliseconds in the output, but with the DataflowRunner we don't get milliseconds, a very strict parser failes on this.
