### ISSUE TITLE
Doc errors: PubSub

### ISSUE THREAD

**Issue by q42jaap** [GoogleCloudPlatform/DataflowJavaSDK#22]
https://cloud.google.com/dataflow/model/reading-and-writing-data#PubsubIO

code examples have a wrong topic format, they are written as `projects/my-project/topics/my-topic` but should be `/topics/my-project/my-topic`.

**Comment by davorbonaci** [comment]
Hi Jaap,
Thanks for reporting this issue. We have addressed it earlier today.

Please let us know if something doesn't seem right. Thanks!
