### ISSUE TITLE
Doc error: Local execution

### ISSUE THREAD

**Issue by q42jaap** [GoogleCloudPlatform/DataflowJavaSDK#23]
https://cloud.google.com/dataflow/pipelines/executing-your-pipeline#LocalExecution

contains two dead links:
* https://cloud.google.com/dataflow/java-sdk/JavaDoc/com/google/cloud/dataflow/sdk/runners/PipelineOptions
* https://cloud.google.com/dataflow/model/constructing-your-pipeline#Configuring

**Comment by davorbonaci** [comment]
Hi Jaap,
Thanks for reporting this issue. We have addressed it earlier today.

Please let us know if something doesn't seem right. Thanks!
