### ISSUE TITLE
Deduplicate error on assembly

### ISSUE THREAD

**Issue by torbjornvatn** [GoogleCloudPlatform/DataflowJavaSDK#246]
I'm using the Dataflow SDK from Scala and when I upgraded from `1.4.0` to `1.5.1` I started to get errors when trying to assemble a jar file. I use the `sbt-assembly` plugin and the error messages looks like the excerpt I've included at the bottom.
It seems like some classes in the `protobuf-java` library has been duplicated in `bigtable-protos`. As mentioned it works just fine with `1.4.0`

```[error] deduplicate: different file contents found in the following:
[error] /Users/torbjorn/.ivy2/cache/com.google.cloud.bigtable/bigtable-protos/jars/bigtable-protos-0.2.3.jar:com/google/protobuf/WrappersProto.class
[error] /Users/torbjorn/.ivy2/cache/com.google.protobuf/protobuf-java/bundles/protobuf-java-3.0.0-beta-1.jar:com/google/protobuf/WrappersProto.class```

**Comment by dhalperi** [comment]
Hi Torbjørn,

This is true -- the bigtable protos jar in question does bundle duplicate copies of some jars. While non-ideal, this should not cause a problem as the copies themselves are identical. Maven shading handles this gracefully, but I've no experience with `sbt`.
