### ISSUE TITLE
[Question] Is anyone working on a BigTable Sink?

### ISSUE THREAD

**Issue by benjumanji** [GoogleCloudPlatform/DataflowJavaSDK#25]
Am very interested. I would be happy to write one if someone were willing to cast an eye it when it is done.

**Comment by ericmand** [comment]
Hi benjumanji, We are super excited to have your contributions! We will definitely cast an eye (we do very detailed code reviews). Also, we'd prefer you give us a couple weeks to straighten out some design suggestions on our side. I'm going to put you in touch with a couple folks who would like to work with you on this and will let you know the outcome of those design suggestions.

**Comment by davorbonaci** [comment]
Cloud BigTable connector is now available, see inside [Cloud BigTable documentation](https://cloud.google.com/bigtable/docs/dataflow-hbase?hl=en). It is packaged as a separate artifact for the time being.

Please report any issues in the [BigTable repository on GitHub](https://github.com/GoogleCloudPlatform/cloud-bigtable-client).
