### ISSUE TITLE
No option for selecting the network that the workers spin up on

### ISSUE THREAD

**Issue by benjumanji** [GoogleCloudPlatform/DataflowJavaSDK#26]
All workers go to default net for the project which while not a deal breaker is a right pain. An option to select a network in `DataflowPipelineWorkerPoolOptions` would be grand.

**Comment by davorbonaci** [comment]
Hi Benjamin,
This sounds like a reasonable feature request. We cannot promise any timeline here, but we'll try to accommodate this.

I'll leave this issue open to track the state of the feature. Please reply back if it becomes blocking, or you have any additional thoughts.

Thanks!

**Comment by dhalperi** [comment]
A fix is in the works. Not certain when it will be rolled out, but I'm on it. Thanks!

**Comment by dhalperi** [comment]
Hi @benjumanji, this feature has been implemented and pushed to GitHub. It should be available in the next Maven release. Feel tree to try it out, and please let us know if you have any issues!

**Comment by benjumanji** [comment]
Hurray! Thanks!
