### ISSUE TITLE
Maven compilation errors caused by out of date Javadoc references.

### ISSUE THREAD

**Issue by Scentus** [GoogleCloudPlatform/DataflowJavaSDK#28]
Attempting to compile the SDK currently fails with an error during javadoc generation. The first two errors seemed to be caused by the use of a relative path to WindowingInternals while the last one is because DoFn.KeyedState was removed recently.

Relevant log:
[ERROR] /home/cal/smplbio/DataflowJavaSDK/sdk/src/main/java/com/google/cloud/dataflow/sdk/transforms/windowing/Trigger.java:84: error: reference not found
[ERROR] *   it may persist book-keeping information to {@link WindowingInternals.KeyedState},
[ERROR] ^
[ERROR] /home/cal/smplbio/DataflowJavaSDK/sdk/src/main/java/com/google/cloud/dataflow/sdk/transforms/windowing/Trigger.java:96: error: reference not found
[ERROR] * {@link WindowingInternals.KeyedState} before the callback returns.
[ERROR] ^
[ERROR] /home/cal/smplbio/DataflowJavaSDK/sdk/src/main/java/com/google/cloud/dataflow/sdk/values/CodedTupleTagMap.java:26: error: reference not found
[ERROR] * {@link com.google.cloud.dataflow.sdk.transforms.DoFn.KeyedState#lookup(java.lang.Iterable)}.
[ERROR] ^

**Comment by davorbonaci** [comment]
Hi Christina,
Yes, this is a bug. It got pushed to GitHub a few hours ago, and Travis CI has just caught it. We are working on this and expect to resolve it later today.

In the meanwhile, you may want to sync to an earlier commit. The issue reproduces on JDK8 only, so you may want to temporarily use JDK7.

Sorry for the trouble.

**Comment by Scentus** [comment]
No problem. Thanks for the heads up.

**Comment by davorbonaci** [comment]
This issue should now be resolved across JDKs.
