### ISSUE TITLE
No table sharding in BigQuery writer.

### ISSUE THREAD

**Issue by benjumanji** [GoogleCloudPlatform/DataflowJavaSDK#29]
Given the big query model this severely limits the utility of streaming into BigQuery. I am going to hack up something over the next couple days, looking for some pointers.

I am guessing that the best thing to offer a template for people to take the window of the element being processed and use that as a template for a dataset name, and output to the table returned by the template function.

Given that there is already a handy static map of schemas, this doesn't seem like it would be too hard to add.

If this is successful and you consider this the right approach, would be happy to offer a PR.

EDIT: clearly just using a static map won't cut it as over a long running streaming app, this is will eventually OOM.

**Comment by benjumanji** [comment]
Just a quick update on this, my approach seems to be working just fine, I haven't benched it. I plan on polishing it a little then opening a PR for discussion.

**Comment by davorbonaci** [comment]
Hi Benjamin,
Tying windows with BigQuery datasets sounds relatively specific and not particularly extensible to the general case. In principle, such functionality doesn't sound like something to include in the mainline SDK.

Are you attempting to write to a set of BigQuery datasets/tables, with the actual layout being data dependent? Perhaps that problem could be attacked by writing to a non-data dependent table layout and using BigQuery features to view a portion of the final table(s).

**Comment by dhalperi** [comment]
For what reason do you want sharding? Could you put the window ID as a column in the BQ and then use that as a filter to mimic the table-per-window semantics you're using now?

**Comment by davorbonaci** [comment]
We have discussed this internally a bit, and it seems reasonable to offer something similar to what you are proposing.

We would suggest a few changes to your approach, however. For example, we'd probably want to do it on the BigQuery table level, not the dataset level. Also, we'd probably want the user to provide a mapping between windows and table names, instead of an automatic inference based on the window.

If you have your code already working and are comfortable with proposing a pull request, please go ahead and submit it as is. Please expect a somewhat longer review and discussion since this change affects the public API.

**Comment by benjumanji** [comment]
I made a mistake in my description, I meant table name, not dataset!

The use case I am targeting is a steaming data flow pushing transaction data to big query, and I would like a new table every day.

I currently have an extra field called shardSuffixTemplate on the big query data connector that is used to format a date. Rows are then sent to the appropriate table based on the window associated with the item.

At the moment the implementation is super cheesy and probably not the _right_ way to do it. Other than using the window from the `ProcessContext` how would you map row to tables? I did have a thought about using group / partition to make sure each pcollection only spanned a single window but that seemed like overkill.

On the review aspect, I once has an @google.com email address, so I know what to expect :)

**Comment by davorbonaci** [comment]
Sounds like you don't particularly like your current implementation. In that case, let us pick this one. We'll work on it and will try to get it done soon.

Let's re-purpose this issue to track the feature request.

**Comment by benjumanji** [comment]
I am happy with that.

**Comment by bjchambers** [comment]
I believe this was addressed in ccad188c19f0e237c6f9cc126cb553d383ad0be6. You should now be able to specify a function for turning a window into a tablespec. Let us know if that covers your intended uses.

**Comment by benjumanji** [comment]
Hi, this is kind of embarrassing that it has taken me this long to really dig into the code / move our jobs off my home brew. One thing that I noticed in the commit is that the createTables structure is still a (static) set. Given that the number of tables created is unbounded as time progresses, I switched this out for a loading cache in my impl. I would be happy to propose a patch.
