### ISSUE TITLE
PipelineOptions is not serializable

### ISSUE THREAD

**Issue by zenlambda** [GoogleCloudPlatform/DataflowJavaSDK#290]
Is there a good reason why PipelineOptions is not serializable?

The following code:
```
    @Test
    public void testSerializeOptions() throws IOException {
        PipelineOptions options = PipelineOptionsFactory.create();

        ByteArrayOutputStream bos = new ByteArrayOutputStream();
        ObjectOutputStream oos = new ObjectOutputStream(bos);

        oos.writeObject(options);
        oos.flush();
    }
```

Yields the following error:

```
java.io.NotSerializableException: com.google.cloud.dataflow.sdk.options.ProxyInvocationHandler

	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
	at net.memberoo.dataflow.SerializeOptionsTest.testSerializeOptions(SerializeOptionsTest.java:20)
```

I encountered this when I made PipelineOptions a member of a WriteOperation in my custom output code. I can of course work around this by pulling out the necessary info out of the PipelineOption object, but since PipelineOptions is in fact serializable via json apis (Jackson?) then this feels a bit counter-intuitive.

**Comment by lukecwik** [comment]
Since PipelineOptions is passed to the user as an argument this allowed the runner to set options which would then be visible to the pipeline author. Also, by having it passed in we could limit the number of instances of more expensive options like credentials and executors. This would be quite difficult to do for arbitrarily serialized java instances as member variables.

Several WriteOperation methods (initialize, finalize, ...) have PipelineOptions being passed in, is there a reason why you need to store a reference to the PipelineOptions in the WriteOperation?

**Comment by zenlambda** [comment]
@lukecwik I can definitely use the PipelineOptions parameter in initialize, finalize etc. There is no specific reason why I need to store a reference to the whole PipelineOptions in the WriteOperation, there are definitely other ways.

I raised this issue because [since PipelineOptions is json serializable](https://github.com/GoogleCloudPlatform/DataflowJavaSDK/blob/master/sdk/src/main/java/com/google/cloud/dataflow/sdk/options/PipelineOptions.java#L193) I wondered whether it was *intentionally __not__*  Java serializable.

It sounds like it is not worth the effort.

**Comment by lukecwik** [comment]
To make the answer explicit, PipelineOptions was made intentionally **NOT** Java serializable.
