### ISSUE TITLE
Combine transforms have no .named("Name") function but have deprecated .withName("Name")

### ISSUE THREAD

**Issue by Scentus** [GoogleCloudPlatform/DataflowJavaSDK#31]
There is no way to perform a chained rename of a Combine transform without the use of the deprecated function .withName("Name") in the latest commit. Other transforms have the .named("Name") function but this was never added to the Combine transforms.

**Comment by davorbonaci** [comment]
Hi Christina,
Thanks for reporting this. Yes, we concur with your analysis and we'll roll out a solution soon.

**Comment by bjchambers** [comment]
Hi Christina. Several changes have gone in that should help with this situation.

Commit 88693d2ee07d54735dfa562f8a019f78955b5cee adds a `.named("Name")` function to `Combine`, which allows changing the name of the Combine transform.

If you just want to set the name for a specific application of a PTransform (eg., to have it show up in the UI, etc.) commit 24718beeb8552bc5c5a7e7c92c2346399b4fb7ce allows specifying a name for the  application of any PTransform:

    pipeline.apply("Name", Combine.perKey(...))

Hope these help!
