### ISSUE TITLE
populateDisplayData doesn't show up on composite PTransform?

### ISSUE THREAD

**Issue by nevillelyh** [GoogleCloudPlatform/DataflowJavaSDK#314]
I have a code snippet that look like this:
```java
.apply(new PTransform<PCollection<String>, PCollection<KV<String, Long>>>("transform") {
  @Override
  public PCollection<KV<String, Long>> apply(PCollection<String> input) {
    return input.apply(Count.<String>perElement());
  }

  @Override
  public void populateDisplayData(DisplayData.Builder builder) {
    builder.add(DisplayData.item("test key", "test val"));
  }
})
```

And the "test key" display data doesn't show up in Dataflow console. Is this expected?

**Comment by bjchambers** [comment]
Hi Neville -- this is indeed an issue with the current SDK. The probelm is related to the Dataflow runner getting rid of all the composites before the pipeline is submitted -- so there is no place to put the DisplayData. We've opened https://issues.apache.org/jira/browse/BEAM-366 to track this feature.

In the meantime, you can add display data to leaf transforms, such as ParDo by populating the display data of the DoFn.
