### ISSUE TITLE
Allow for user controlled unique id in BigQuery Write

### ISSUE THREAD

**Issue by benjumanji** [GoogleCloudPlatform/DataflowJavaSDK#32]
If we do a streaming write, the write connector will generate unique ids and tag rows transparently to avoid duplication. If the user knows something about their data like "the transaction-id column is unique across the table", it would be nice to be able to use that instead of the generated ids.

**Comment by q42jaap** [comment]
+1

**Comment by dovy** [comment]
+1

**Comment by dhalperi** [comment]
My understanding of this FR is that users typically think this will help them de-dupe across *jobs* or long periods of time. These row-IDs are very short-lived (1 minute). So it does not make sense to let users control them.

If you have some other ID you can de-dupe with, they can use GroupByKey or RemoveDuplicates within your pipeline to do so.
