### ISSUE TITLE
Dataflow write to BQ without schema in streaming pipelines

### ISSUE THREAD

**Issue by srfrnk** [GoogleCloudPlatform/DataflowJavaSDK#342]
Given the following:

- [CREATE_NEVER create disposition is not supported for streaming mode and as default one is CREATE_IF_NEEDED that requires schema, it doesn't look possible. I will look into this further and provide another update on Monday.](https://github.com/GoogleCloudPlatform/DataflowJavaSDK/blob/master/sdk/src/main/java/com/google/cloud/dataflow/sdk/io/BigQueryIO.java#L1694)
- [ schema is required only if writing to a table that does not already exist, and BigQueryIO.Write.CreateDisposition is set to BigQueryIO.Write.CreateDisposition.CREATE_IF_NEEDED. So you can use CREATE_NEVER CreateDisposition and WRITE_APPEND WriteDisposition to create write transformation that wouldn't require schema.
](https://cloud.google.com/dataflow/java-sdk/JavaDoc/com/google/cloud/dataflow/sdk/io/BigQueryIO.Write#withSchema-com.google.api.services.bigquery.model.TableSchema-)

It is impossible at this time to use a Dataflow streaming pipeline to write to BQ without specifying a hard-coded schema.

This is a major problem because streaming pipelines are meant to be kept running continuously and table schema changes require you to re-deploy new versions!

**Comment by srfrnk** [comment]
This was raised as an internal feature request 30242703
Please link to FR if possible so I can track progress.

**Comment by dhalperi** [comment]
Starting with version 2.0, Google Cloud Dataflow SDK for Java will be based on Apache Beam -- with code in [apache/incubator-beam](https://github.com/apache/incubator-beam/). I've filed this as a feature request on the Apache Beam JIRA issue tracker: https://issues.apache.org/jira/browse/BEAM-476.
