### ISSUE TITLE
Local pusub runner

### ISSUE THREAD

**Issue by benjumanji** [GoogleCloudPlatform/DataflowJavaSDK#35]
Currently it is not possible to run streaming pipelines with the direct runner if they involve a pubsub component. Local translator that created a simple publisher / pull subscriber would be very helpful.

**Comment by davorbonaci** [comment]
Hi Benjamin,
Yes, this is a gap and it is on our radar. I'll keep this issue open, so we can occasionally post an update. (External contributions are welcome.)

Thanks!

**Comment by davorbonaci** [comment]
Dataflow pipelines reading via `PubSubIO` can now be executed using `DirectPipelineRunner`. You'd have to use `maxNumRecords` and/or `maxReadTime` to construct a bounded `PCollection`.
