### ISSUE TITLE
Kafka 0.10 support

### ISSUE THREAD

**Issue by criccomini** [GoogleCloudPlatform/DataflowJavaSDK#353]
Do you guys have plan to move the Kafka contrib package from 0.9.0.1 to 0.10.0.0? I acknowledge that the client-side should be compatible with 0.10 brokers, but we're depending on third party serialization libraries that pull in Kafka 0.10. There are binary incompatible changes between 0.9.0.1 and 0.10's consumer API (they changed some methods from varargs list to Collections).

**Comment by dhalperi** [comment]
I think this issue has been addressed in Dataflow SDK for Java version 2 based on [Apache Beam](https://beam.apache.org).
