### ISSUE TITLE
Adding header in text files

### ISSUE THREAD

**Issue by abhishek-jha13** [GoogleCloudPlatform/DataflowJavaSDK#360]
Is there any estimated time in which TextIO sink will support adding header to the sink files?

**Comment by lukecwik** [comment]
No timeline, cut feature request:
https://issues.apache.org/jira/browse/BEAM-544

Please add any additional comments to the issue linked above.

**Comment by lukecwik** [comment]
Backporting adding support for header/footer to TextIO sinks with
https://github.com/GoogleCloudPlatform/DataflowJavaSDK/pull/423

**Comment by lukecwik** [comment]
This was released part of the Dataflow 1.7.0 SDK
