### ISSUE TITLE
PubsubIO deletes context

### ISSUE THREAD

**Issue by q42jaap** [GoogleCloudPlatform/DataflowJavaSDK#37]
A pubsub message, when consumed by a custom subscription, has more information than just the payload:
{"message": {"attributes": {}, "data": "some-base64-data", "message_id": "84531668664"}, "subscription": "projects/<projectid>/subscriptions/<subscriptionid>"}

Specifically attributes might be something you'd want. There should be a codec that handles this.

pseudo-code:
```
class PubsubMessage {
  String subscription;
  String json; // or some other type
  Map<String, String> attributes; // or some other type...
}
```

**Comment by davorbonaci** [comment]
Hi Jaap,
We concur with your analysis. This is not trivial, as we need to clarify the interaction between coders and sources/sinks. I'll keep this issue open, so we can occasionally post an update.

Thanks!

**Comment by mmargetts** [comment]
Hi davorbonaci,
Just wanted to see if there is any progress on this request.   

Thanks

**Comment by davorbonaci** [comment]
No particular update at this time. If this is becomes blocking, please let us know.

**Comment by dhalperi** [comment]
This is being tracked as part of [BEAM-53](https://issues.apache.org/jira/browse/BEAM-53)
