### ISSUE TITLE
[question] Bundle relationship to Windows / Grouping keys

### ISSUE THREAD

**Issue by benjumanji** [GoogleCloudPlatform/DataflowJavaSDK#38]
I am currently working on a Cassandra Connector, at the moment it's just the write aspect of it. One thing that is nice / interesting about Cassandra is that it will resolve multiple inserts to the same partition key to a single write. If there was some way to force a bundles to have the same partition key somehow it could enable some nice optimisations: for streaming writes you could use cql batches to nice effect and in batch mode you could do some of the tricks that the datastax spark connector does and grab the token ring and send the data to the correct nodes directly without a coordinator.

Is there any way to reason about these types of things? I have been reading all the impls in the SDK for BigQuery / DataStore but this type of thing doesn't seem to be in there.

**Comment by davorbonaci** [comment]
I apologize for a super late response here!

In general, Dataflow doesn't provide a direct way to control sharding, i.e., to control how many bundles will there be, or how elements will be distributed across those bundles. We think that it should *not* be needed to worry about sharding on a per-step level.

When it comes to sources and sinks, sometimes bundling controls become necessary. We provide built-in features in some cases, e.g., `withNumShards` in `TextIO`. We are working on generalizing this and proving bundling controls across custom IO.

That said, similar behavior may be achieved via our `GroupByKey` transform by grouping elements based on their partition key. If you have a `PCollection<T>`, you can apply a `ParDo` that transforms it into `PCollection<KV<Key, T>>`, where the key corresponds to the partition key of your sink. After `GroupByKey`, you get a `PCollection<Key, Iterable<T>>`, which now guarantees that elements with the same key are processed as a single element. Keep in mind that this approach may slow down your pipeline, depending on the distribution of data.

Hope this helps!
