### ISSUE TITLE
BigQuery IO doesnt support ignoreUnknownValues

### ISSUE THREAD

**Issue by sushantk** [GoogleCloudPlatform/DataflowJavaSDK#380]
It will be great to support ignoreUnknownValues to help with schema evolution so that we can continue to ingest data set with new attributes which are not added to the corresponding BigQuery table schema yet.

The configuration option is listed here:
https://cloud.google.com/bigquery/docs/reference/v2/tables

**Comment by Temikus** [comment]
@dhalperi Daniel, can you please take a look? Is this something that's planned?

**Comment by dhalperi** [comment]
If this happens, it will be in Dataflow 2.x, which will be based on Apache Beam. For more information, see the [Dataflow 2.x release notes](https://cloud.google.com/dataflow/release-notes/release-notes-java-2). You may also be interested in the [JIRA issue tracker for Apache Beam , `sdk-javagcp` (Google Cloud Platform) component](https://issues.apache.org/jira/issues/?jql=project%20%3D%20BEAM%20AND%20status%20in%20(Open%2C%20%22In%20Progress%22%2C%20Reopened)%20AND%20component%20%3D%20sdk-java-gcp).

We of course welcome feature requests as new JIRA issues or +1s on existing issues. I believe there is an existing feature request: [BEAM-1267](https://issues.apache.org/jira/browse/BEAM-1267) with a Pull Request that is in progress.

**Comment by dhalperi** [comment]
Also, here's the contribution guide for Apache Beam, with more detailed
information on all of the above.
https://beam.apache.org/contribute/contribution-guide/#engage
