### ISSUE TITLE
Expose System Watermark

### ISSUE THREAD

**Issue by benjumanji** [GoogleCloudPlatform/DataflowJavaSDK#39]
We would love to do alerting if certain jobs / transform fall behind or trigger external work based on where the processing time is in the system. Ideally it would be nice if this was exposed via cloud metrics, but I would accept anything that allowed me to get my hands on the timestamp directly.

If there is a simple enough way to achieve this with triggers I am open to it, but I don't want the data _in_ the pane, I just want to know the progress.

**Comment by davorbonaci** [comment]
Hi Benjamin,
Triggers are not intended for this purpose. Sounds like you want to monitor the pipeline progress outside of the job execution environment for monitoring and alerting purposes. This is a reasonable use case -- but I'd like to note that the system watermark should *not* be, in general, programmatically accessed in the job execution environment.

A way to do this currently is via our `gcloud` command:

    gcloud alpha dataflow --project=PROJECT_NAME metrics tail JOB_ID --tentative

The output should contain something like this:

    name:
     context:
       stage: F5
       tentative: 'true'
     name: windmill-data-watermark
     origin: dataflow/v1b3
    scalar: 1432085644000
    updateTime: '2015-05-20T01:34:13.333Z'

See our [documentation](https://cloud.google.com/dataflow/pipelines/dataflow-command-line-intf) for more information.

That said, integration with [Cloud Monitoring](https://cloud.google.com/monitoring) is something that we are interested in, but I don't have any information to share at this point.

**Comment by Aki11es** [comment]
Huh.

**Comment by benjumanji** [comment]
@davorbonaci that's great that it's in the gcloud tool. It would also be nice if it were _more_ machine readable (I get that I can totally parse that output, and I probably will write something to do just that).

**Comment by davorbonaci** [comment]
The output of `gcloud`, by default, is in YAML format. As such, it is automatically parsable by various libraries. Additionally, I believe there is `--format` option in `gcloud` to change it to JSON if that is easier for you.

Please note, however, the `alpha` argument in `gcloud alpha dataflow` indicates that this functionality is in Alpha, and it is subject to change.

**Comment by benjumanji** [comment]
Well that will teach me to comment without reading. Thanks. The `alpha` is noted.
