### ISSUE TITLE
Issue with SDK 1.6.0 when running DataflowPipelineRunner on App Engine

### ISSUE THREAD

**Issue by nlokare** [GoogleCloudPlatform/DataflowJavaSDK#402]
Still encountering issues with SDK 1.6.0 similar to https://github.com/GoogleCloudPlatform/DataflowJavaSDK/issues/204 with a similar use case.

Still seeing this error:
```
Error for /
org.xerial.snappy.SnappyError: [FAILED_TO_LOAD_NATIVE_LIBRARY] null
```

even after including `org.xerial.snappy` in our `pom.xml`. Will this still only work in a Flex VM and not as an AppEngine module?

**Comment by dhalperi** [comment]
This is still working as intended; AppEngine standard is not a supported use case for the Cloud Dataflow SDK for Java.

**Comment by nlokare** [comment]
@dhalperi Ok, thank you.
