### ISSUE TITLE
Idea: MapValues transform

### ISSUE THREAD

**Issue by trentonstrong** [GoogleCloudPlatform/DataflowJavaSDK#412]
Often I find myself needing to simply map a function over just the values of a key-valued PCollection. MapElements works for this, but suffers a small hit in readability (imho) and introduces some possibility for error.

I wanted to see if there is any bandwidth / interest in adding this as a standard transform to the SDK. If so, I have attached a gist with a basic spike I have been using in my flows:

[MapValues](https://gist.github.com/trentonstrong/8b60933dca545eb2138b72899195019e)

Thanks.

**Comment by lukecwik** [comment]
Most active development for Google Cloud Dataflow has been happening on Apache Beam with backports going here.

I have filed your idea for discussion here:
https://issues.apache.org/jira/browse/BEAM-611
