### ISSUE TITLE
Add a way to close a pipeline

### ISSUE THREAD

**Issue by tomwhite** [GoogleCloudPlatform/DataflowJavaSDK#42]
It would be useful to have a `close()` method on `Pipeline` so that its resources can be properly disposed of. For example, in the case of Spark Dataflow (https://github.com/cloudera/spark-dataflow), calling close would stop the Spark execution context.

**Comment by dhalperi** [comment]
Sounds like this is related to https://issues.apache.org/jira/browse/BEAM-849 , which will be addressed in Beam. It may also be directly related to the Beam `SparkRunner`.
