### ISSUE TITLE
DataflowAssert serde cycle on actual values

### ISSUE THREAD

**Issue by ravwojdyla** [GoogleCloudPlatform/DataflowJavaSDK#434]
Afaiu `CheckRelationAgainstExpected` from [DataflowAssert](https://github.com/GoogleCloudPlatform/DataflowJavaSDK/blob/master/sdk/src/main/java/com/google/cloud/dataflow/sdk/testing/DataflowAssert.java#L1022), it does serde cycle on expected values, while actual values coming from PCollection would not go through the same cycle. This may lead to inconsistency, for example in case of TableRow/TableRowJsonCoder/Jackson:
   
  * http://stackoverflow.com/questions/33622227/dataflow-mixing-integer-long-types
  * http://stackoverflow.com/questions/7316689/forcing-jackson-to-deserialize-to-specific-primitive-type

What do you think about enforcing serde cycle on PCollection before matching with `expected` values?

This issue came up in spotify/scio#252

**Comment by ravwojdyla** [comment]
We have introduced serde cycle in scio via [#253](https://github.com/spotify/scio/pull/253/commits/efe12ca86dab52d75dd94f72197015e5e9afd018) and this solved the problem (spotify/scio#252) of inconsistency of TableRows for us. Should I go for it and push a PR to move it to DFAssert?

**Comment by dhalperi** [comment]
Interesting point, maybe @tgroh has thoughts.

**Comment by ravwojdyla** [comment]
@dhalperi - @tgroh already created PR (?). Is there something more we should discuss?

**Comment by tgroh** [comment]
The PR exists, but I haven't had time to investigate why the JDK7 builds time out/oom in the BoundedReadFromUnboundedSourceTest; in terms of "work performed" the pipelines should be the same, but the use of the cloned elements seems to be breaking something

**Comment by ravwojdyla** [comment]
@tgroh do you plan to finish the PR?

**Comment by ravwojdyla** [comment]
ping @tgroh

**Comment by tgroh** [comment]
I do. I've reduced the amount of time spent reading in the one test that seemed to repeatedly fail, and Travis seems to be happier.
