### ISSUE TITLE
Example Document Links are Broken

### ISSUE THREAD

**Issue by sirinath** [GoogleCloudPlatform/DataflowJavaSDK#45]
E.g. https://github.com/GoogleCloudPlatform/DataflowJavaSDK/blob/master/examples/src/main/java/com/google/cloud/dataflow/examples/JoinExamples.java

This is in: https://github.com/GoogleCloudPlatform/DataflowJavaSDK/blob/master/examples/README.md

**Comment by davorbonaci** [comment]
Hi Suminda,
This was fixed in #52.

Thanks!
