### ISSUE TITLE
DatastoreV1beta2

### ISSUE THREAD

**Issue by Pega88** [GoogleCloudPlatform/DataflowJavaSDK#457]
Hi,
Your setup is made to use

<datastore.version>v1beta2-rev1-4.0.0</datastore.version>

However this gets deprecated today. Could you update to a supported version?
Your release notes state that dataflow sdk v1.7.0 should include this,however your pom.xml on master branch still uses the v1beta2.

Thanks!

**Comment by lukecwik** [comment]
We will depend on this library to allow peoples code to compile and will not break backwards compatibility for them. They may still use the data types as an intermediate representation in their pipeline. There is no expectation that this will work against the Datastore service as support for this version is being turned down.

This has already been removed from Apache Beam for the next major version release.

**Comment by dhalperi** [comment]
Specifically, there is now a version of Datastore that uses the V1 API; all customers should use that instead. [DatastoreIO.v1()](https://github.com/GoogleCloudPlatform/DataflowJavaSDK/blob/master/sdk/src/main/java/com/google/cloud/dataflow/sdk/io/datastore/DatastoreIO.java)
