### ISSUE TITLE
Tagged artifacts versions are SNAPSHOTs

### ISSUE THREAD

**Issue by roundbatman** [GoogleCloudPlatform/DataflowJavaSDK#464]
I don't think this is a good practice and it's not in line with the other Java projects under GoogleCloudPlatform.

Found this out as I was hunting for examples and noticed that they depend on SNAPSHOT version after checking out a 1.7.0 tag.

Br,

       -juha

**Comment by dhalperi** [comment]
cc: @davorbonaci 

This is an explicit choice we made: if you check out the tag, you are necessarily not using our released artifact, and we want to be able to distinguish the difference.
