### ISSUE TITLE
A bug related to the per-window table names.

### ISSUE THREAD

**Issue by mbarragan** [GoogleCloudPlatform/DataflowJavaSDK#48]
I've tried to use the bellow example that there is in BigQueryIO.java:

<pre>
PCollection<TableRow> quotes = ...

List<TableFieldSchema> fields = new ArrayList<>();
fields.add(new TableFieldSchema().setName("source").setType("STRING"));
fields.add(new TableFieldSchema().setName("quote").setType("STRING"));
TableSchema schema = new TableSchema().setFields(fields);

quotes.apply(BigQueryIO.Write
  .named("Write")
  .to("my-project:output.output_table")
  .withSchema(schema)
  .withWriteDisposition(BigQueryIO.Write.WriteDisposition.WRITE_TRUNCATE));
</pre>

And the bellow error has appeared:

<pre>
Exception: java.lang.IllegalArgumentException: Table reference is not in [project_id]:[dataset_id].[table_id] format: my-project:output.output_table-[2015-07-24:00:00.000Z..2015-07-25T00:00:00.000Z)
</pre>

This is actually incorrect, since it appears to generate strings that are not legal in BigQuery table names.

**Comment by davorbonaci** [comment]
Thanks for this bug report. I can confirm the issue was fixed in commit 2116e5b4dc58920cbe00006871129ccf89d8daec.

Please let us know if you see any additional issues. Thanks!
