### ISSUE TITLE
How to use a serviceAccount

### ISSUE THREAD

**Issue by rockwotj** [GoogleCloudPlatform/DataflowJavaSDK#483]
I am having a hard time running my dataflow job with a service account (I'm trying to set it up as a cron on a machine). I figured out that I need to use a p12 file instead of a JSON file, from reading the source. But now I'm getting a 401: Unable to verify that GCS bucket. I'm using `GcpOptions` and  the command line flags `--serviceAccountKeyfile="dataflow-service-account.p12" --serviceAccountName="dataflow"` the service account has edit access to the whole project, so I'm unsure what I'm doing wrong.

**Comment by lukecwik** [comment]
Were you able to find the documentation about application default credentials:
https://developers.google.com/identity/protocols/application-default-credentials#howtheywork

They support the credentials packaged up as JSON files and have several ways listed as to how to use them.

The serviceAccountKeyfile and serviceAccountName are for backwards compatibility for users before application default credentials became available.

**Comment by rockwotj** [comment]
Yupp found it, thanks.
