### ISSUE TITLE
Native support for conditional iteration 

### ISSUE THREAD

**Issue by bjchambers** [GoogleCloudPlatform/DataflowJavaSDK#50]
There are a variety of use cases which would benefit from native support for conditional iteration.

For instance, http://stackoverflow.com/questions/31654421/conditional-iterations-in-google-cloud-dataflow/31659923?noredirect=1#comment51264604_31659923 asks about being able to write a loop like the following:

```
PCollection data  = ...
while(needsMoreWork(data)) {
  data = doAStep(data)
}
```

If there are specific use cases please let us know the details. In the future we will use this issue to post progress updates.

**Comment by lukecwik** [comment]
Migration of this request has been ported to BEAM: https://issues.apache.org/jira/browse/BEAM-106
