### ISSUE TITLE
Is the immutable requirement for ParDo really necessary?

### ISSUE THREAD

**Issue by nevillelyh** [GoogleCloudPlatform/DataflowJavaSDK#53]
Referring to this [commit](https://github.com/GoogleCloudPlatform/DataflowJavaSDK/commit/ca2d22e198212c38e76b8b91ae8698dc2d877666). Is the immutable requirement really necessary? Some data structures, i.e. PriorityQueue, relies on mutable operation for performance reasons. And since users always map their data to such structures and fold in place, there's little concern of incorrectness.

**Comment by bjchambers** [comment]
The issue with immutability is that the service may fuse multiple `DoFn` operations together, so it is not safe to modify any of the inputs/outputs. As an example, if you had the following pipeline:

```
PCollection<PriorityQueue> queues = pipeline.apply(ParDo.of(new ProduceQueuesFn()));
queues.apply(ParDo.of(new ModifyQueuesFn());
queues.apply(ParDo.of(new PrintQueuesFn());
```

The service would likely fuse all 3 of these operations into a single step and the `PriorityQueue` would not be cloned (or serialized/deserialized) in between any of the `DoFn` calls. As a result `PrintQueuesFn` would be invoked on the same object that was passed to `ModifyQueuesFn` which may have been modified from when it was outputted by `ProduceQueuesFn`.

If you want to use a `PriorityQueue` and modify it within a `DoFn`, you should clone it within the code for that `DoFn` to ensure that you don't mutate any of your inputs/outputs.

**Comment by nevillelyh** [comment]
Make sense. I switched to an immutable approach. Thanks.
