### ISSUE TITLE
BigQueryIO.Read needs a GCS temp location to store temp files.

### ISSUE THREAD

**Issue by demousteven** [GoogleCloudPlatform/DataflowJavaSDK#542]
I keep on having this problem when executing BigQueryTornadoes :
this is my config file :
mvn compile exec:java \
-Dexec.mainClass=com.google.cloud.dataflow.examples.cookbook.BigQueryTornadoes \
-Dexec.args="--project=dev6celbux \
--output=dev6celbux:dev6celbux.Count_table\
--tempLocation=gs://project_autocomplete/BigQueryTornadoes/temp
--stagingLocation=gs://project_autocomplete/BigQueryTornadoes/staging
--runner=BlockingDataflowPipelineRunner"

**Comment by davorbonaci** [comment]
Can you please comment more on the specific problem you are seeing?

**Comment by davorbonaci** [comment]
Sounds like a duplicate of #541. Closing.
