### ISSUE TITLE
Need a Sink/Source for Spanner

### ISSUE THREAD

**Issue by NextDevBoard** [GoogleCloudPlatform/DataflowJavaSDK#552]
I would imagine that Google will eventually provide this.   If it is currently in-progress I would love to know because I need it ASAP.   I will give it a shot if no one is engaged on this.

**Comment by dhalperi** [comment]
Hi @NextDevBoard, we are unlikely to add this support to Dataflow 1.x, as we are moving onto [Dataflow 2.x](https://cloud.google.com/dataflow/release-notes/release-notes-java-2) based on [Apache Beam](https://beam.apache.org).

Please file a feature request in the [Apache Beam JIRA under the `sdk-java-gcp` component](https://issues.apache.org/jira/browse/BEAM/component/12328917/?selectedTab=com.atlassian.jira.jira-projects-plugin:component-summary-panel) instead.
