### ISSUE TITLE
@DefaultCoder not honored for parameterized types

### ISSUE THREAD

**Issue by kennknowles** [GoogleCloudPlatform/DataflowJavaSDK#57]
Suppose one writes this:

```
@DefaultCoder(AvroCoder.class)
class MyGenericType<T> {
   ...
}
```

Unfortunately, even if `AvroCoder` could encode this type, it will not be invoked.

**Comment by dhalperi** [comment]
See also: http://stackoverflow.com/questions/32487610/setting-custom-coders-handling-parameterized-types
