### ISSUE TITLE
Add namespace support for Cloud Datastore to perform easy migration.

### ISSUE THREAD

**Issue by chandra-vs** [GoogleCloudPlatform/DataflowJavaSDK#59]
I am currently performing the migration using a single machine which runs sequentially and reads the Entities from the namespaces which is painful for me. Is it possible to use Google Cloud Dataflow to perform the migration easier?

Also this issue has been discussed in Stackoverflow.
http://stackoverflow.com/questions/32584187/how-can-i-perform-migration-of-cloud-datastore-entities-using-dataflow/32657626#32657626

**Comment by dhalperi** [comment]
Thanks @chandra-vs ! We are working on this and will update this issue when completed.
