### ISSUE TITLE
Eclipse plugin fails to initialize due to missing archetype artifact

### ISSUE THREAD

**Issue by swegner** [GoogleCloudPlatform/DataflowJavaSDK#604]
Reported via: https://stackoverflow.com/questions/46086563/google-cloud-dataflow-eclipse-project-cannot-be-created

When creating a new Dataflow project using the Eclipse plugin, users receive an error:

    Could not resolve archetype com.google.cloud.dataflow:google-cloud-dataflow-java-archety‌​pes-starter:2.1.0 from any of the configured repositories.

Taking a look at [Maven Central](https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.google.cloud.dataflow%22) for `com.google.cloud.dataflow`, I see 2.1.0 artifacts published for the SDK, but the latest version for `google-cloud-dataflow-java-archetypes-*` are 2.0.0.

This is preventing new projects to be created using the Eclipse plugin.

**Comment by lukecwik** [comment]
2.1.0 archetypes are now released, see http://central.maven.org/maven2/com/google/cloud/dataflow/
