### ISSUE TITLE
withNamespace() is missing in the DatastoreIO class

### ISSUE THREAD

**Issue by chandra-vs** [GoogleCloudPlatform/DataflowJavaSDK#63]
I created a sample Cloud Dataflow Java project using dataflow Eclipse plugin, I wanted to create a pipeline for DatastoreIO with namespace support, but i couldn't find the withNamespace() in the DatastoreIO class.

**Comment by dhalperi** [comment]
DatastoreIO namespace support is available if you build the development version of the SDK from GitHub, however this version has not yet been released on Maven.

If you would like to use the DatastoreIO namespace support before that release happens, you can install the development version of the SDK using following the [`Getting Started` instructions](https://github.com/GoogleCloudPlatform/DataflowJavaSDK#getting-started). The Eclipse project should then automatically pick up the new version, and if it does not you can edit the project `pom.xml` to manually specify the desired `1.1.1-SNAPSHOT` version with these changes.

**Comment by dhalperi** [comment]
Datastore 1.2.0 is now out, so you should not need to install the development version of the SDK any longer.
