### ISSUE TITLE
Cannot set region for BigQuery dataset when using direct runner using Apache Beam

### ISSUE THREAD

**Issue by doduythao** [GoogleCloudPlatform/DataflowJavaSDK#635]
Cannot set region for BigQuery dataset when using direct runner using Apache Beam. I'm trying to get data from Oracle via JdbcIO.read using apache beam to get data and push them to bigquery table. Problem is I have to use direct runner because Oracle DB is local, and the bigquery dataset must located in asia, not the default us-central. so now I cannot push data because the default location dont have my target dataset. I tried extending the GcpOption but no help. Don't suggest me to use the DataflowRunner, because it cannot load data from Oracle local. Thanks.

**Comment by lukecwik** [comment]
Since your using the DirectRunner, I would suggest you modify the https://github.com/apache/beam/blob/master/sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryServicesImpl.java implementation and pass through the region you want to use.

If you make this extensible, feel free to contribute this back to the Apache Beam Community as others may want this as well.

**Comment by doduythao** [comment]
How can I modify the BigQueryServicesImpl.java, and also there is no option inside to change the region.

**Comment by lukecwik** [comment]
I noticed that the BigQueryIO.java already attempts to find the location automatically based upon the dataset here: https://github.com/apache/beam/blob/0e1dcccf2fbc3737c72cd52fd3eb2018b586c85c/sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryHelpers.java#L212

What if you create the dataset first in the region you want it to be in, does the code in BigQueryHelpers then return the correct location?

Otherwise you'll want to add an option which allows for the dataset location to be explicitly set and update the corresponding logic within BigQueryIO/BigQueryHelpers.java. The Apache Beam contribution guide provides details on how to get the code, build it, and contribute back: https://beam.apache.org/contribute/contribution-guide/

**Comment by doduythao** [comment]
Here the log I get:
May 08, 2018 9:41:55 AM vn.com.momo.analytics.JdbcToBigQuery main
INFO: creating option
May 08, 2018 9:41:58 AM vn.com.momo.analytics.JdbcToBigQuery main
INFO: creating pipeline
May 08, 2018 9:41:58 AM vn.com.momo.analytics.JdbcToBigQuery main
INFO: getting connection
May 08, 2018 9:41:58 AM vn.com.momo.analytics.JdbcToBigQuery main
INFO: SQL :SELECT * FROM mis_admin.MIS_ACCOUNT WHERE ROWNUM <=10 
May 08, 2018 9:42:00 AM vn.com.momo.analytics.JdbcToBigQuery main
INFO: running pipeline
Exception in thread "main" org.apache.beam.sdk.Pipeline$PipelineExecutionException: java.lang.RuntimeException: Failed to create load job with id prefix 2fec46a118634a7f8e67d6f8753d1512_28f0784b6adf4a72e2a27dc45e17b5a9_00001_00000, reached max retries: 3, last failed load job: {
  "configuration" : {
    "load" : {
      "createDisposition" : "CREATE_IF_NEEDED",
      "destinationTable" : {
        "datasetId" : "thaodo",
        "projectId" : "momovn-test",
        "tableId" : "MIS_ACCOUNT_20180508"
      },
      "schema" : {
        "fields" : [ {
          "name" : "ID",
          "type" : "FLOAT"
        }, {
          "name" : "ACC_PHONE",
          "type" : "STRING"
        }, {
          "name" : "PRIMARY",
          "type" : "STRING"
        }, {
          "name" : "PROFILE_ID",
          "type" : "FLOAT"
        }, {
          "name" : "START_DATE",
          "type" : "TIMESTAMP"
        }, {
          "name" : "END_DATE",
          "type" : "TIMESTAMP"
        } ]
      },
      "sourceFormat" : "NEWLINE_DELIMITED_JSON",
      "sourceUris" : [ "gs://test-hieu/tmp/BigQueryWriteTemp/2fec46a118634a7f8e67d6f8753d1512/1e21b450-92cb-4a5b-962b-883333a60701", "gs://test-hieu/tmp/BigQueryWriteTemp/2fec46a118634a7f8e67d6f8753d1512/22cd1016-8d8f-43e9-941e-6c4346351bef", "gs://test-hieu/tmp/BigQueryWriteTemp/2fec46a118634a7f8e67d6f8753d1512/4f78e230-007e-4e9e-85bf-7f2547951385", "gs://test-hieu/tmp/BigQueryWriteTemp/2fec46a118634a7f8e67d6f8753d1512/85db96b6-6410-4711-8ac1-274c3314e28f", "gs://test-hieu/tmp/BigQueryWriteTemp/2fec46a118634a7f8e67d6f8753d1512/5990d321-e710-42df-9573-dc1360f5b154", "gs://test-hieu/tmp/BigQueryWriteTemp/2fec46a118634a7f8e67d6f8753d1512/677062b1-91a0-433b-937e-ca68b8c13692", "gs://test-hieu/tmp/BigQueryWriteTemp/2fec46a118634a7f8e67d6f8753d1512/9c1520bc-a5dd-411e-aa04-b6e138fb8897", "gs://test-hieu/tmp/BigQueryWriteTemp/2fec46a118634a7f8e67d6f8753d1512/9573f1d0-1742-4e04-8a2c-cbf9cd9f990e", "gs://test-hieu/tmp/BigQueryWriteTemp/2fec46a118634a7f8e67d6f8753d1512/40a5b885-be18-4de5-8b1a-18cd4a7e2705", "gs://test-hieu/tmp/BigQueryWriteTemp/2fec46a118634a7f8e67d6f8753d1512/99bf2a23-b82d-444a-b286-2e9667b4e180" ],
      "writeDisposition" : "WRITE_TRUNCATE"
    }
  },
  "etag" : "\"8-EGZnPk12W9PiVn0ZRpZVdMBYs/RYObXstf1bVDNaEj4k7hDizD8UQ\"",
  "id" : "momovn-test:2fec46a118634a7f8e67d6f8753d1512_28f0784b6adf4a72e2a27dc45e17b5a9_00001_00000-2",
  "jobReference" : {
    "jobId" : "2fec46a118634a7f8e67d6f8753d1512_28f0784b6adf4a72e2a27dc45e17b5a9_00001_00000-2",
    "projectId" : "momovn-test"
  },
  "kind" : "bigquery#job",
  "selfLink" : "https://www.googleapis.com/bigquery/v2/projects/momovn-test/jobs/2fec46a118634a7f8e67d6f8753d1512_28f0784b6adf4a72e2a27dc45e17b5a9_00001_00000-2",
  "statistics" : {
    "creationTime" : "1525747335309",
    "endTime" : "1525747335436",
    "startTime" : "1525747335436"
  },
  "status" : {
    "errorResult" : {
      "message" : "Not found: Dataset momovn-test:thaodo. Please verify that the dataset exists and the correct location was used for the job.",
      "reason" : "notFound"
    },
    "errors" : [ {
      "message" : "Not found: Dataset momovn-test:thaodo. Please verify that the dataset exists and the correct location was used for the job.",
      "reason" : "notFound"
    } ],
    "state" : "DONE"
  },
  "user_email" : "etl-bigquery@momovn-test.iam.gserviceaccount.com"
}.
	at org.apache.beam.runners.direct.DirectRunner$DirectPipelineResult.waitUntilFinish(DirectRunner.java:342)
	at org.apache.beam.runners.direct.DirectRunner$DirectPipelineResult.waitUntilFinish(DirectRunner.java:312)
	at org.apache.beam.runners.direct.DirectRunner.run(DirectRunner.java:206)
	at org.apache.beam.runners.direct.DirectRunner.run(DirectRunner.java:62)
	at org.apache.beam.sdk.Pipeline.run(Pipeline.java:311)
	at org.apache.beam.sdk.Pipeline.run(Pipeline.java:297)
	at vn.com.momo.analytics.JdbcToBigQuery.main(JdbcToBigQuery.java:195)
Caused by: java.lang.RuntimeException: Failed to create load job with id prefix 2fec46a118634a7f8e67d6f8753d1512_28f0784b6adf4a72e2a27dc45e17b5a9_00001_00000, reached max retries: 3, last failed load job: {
  "configuration" : {
    "load" : {
      "createDisposition" : "CREATE_IF_NEEDED",
      "destinationTable" : {
        "datasetId" : "thaodo",
        "projectId" : "momovn-test",
        "tableId" : "MIS_ACCOUNT_20180508"
      },
      "schema" : {
        "fields" : [ {
          "name" : "ID",
          "type" : "FLOAT"
        }, {
          "name" : "ACC_PHONE",
          "type" : "STRING"
        }, {
          "name" : "PRIMARY",
          "type" : "STRING"
        }, {
          "name" : "PROFILE_ID",
          "type" : "FLOAT"
        }, {
          "name" : "START_DATE",
          "type" : "TIMESTAMP"
        }, {
          "name" : "END_DATE",
          "type" : "TIMESTAMP"
        } ]
      },
      "sourceFormat" : "NEWLINE_DELIMITED_JSON",
      "sourceUris" : [ "gs://test-hieu/tmp/BigQueryWriteTemp/2fec46a118634a7f8e67d6f8753d1512/1e21b450-92cb-4a5b-962b-883333a60701", "gs://test-hieu/tmp/BigQueryWriteTemp/2fec46a118634a7f8e67d6f8753d1512/22cd1016-8d8f-43e9-941e-6c4346351bef", "gs://test-hieu/tmp/BigQueryWriteTemp/2fec46a118634a7f8e67d6f8753d1512/4f78e230-007e-4e9e-85bf-7f2547951385", "gs://test-hieu/tmp/BigQueryWriteTemp/2fec46a118634a7f8e67d6f8753d1512/85db96b6-6410-4711-8ac1-274c3314e28f", "gs://test-hieu/tmp/BigQueryWriteTemp/2fec46a118634a7f8e67d6f8753d1512/5990d321-e710-42df-9573-dc1360f5b154", "gs://test-hieu/tmp/BigQueryWriteTemp/2fec46a118634a7f8e67d6f8753d1512/677062b1-91a0-433b-937e-ca68b8c13692", "gs://test-hieu/tmp/BigQueryWriteTemp/2fec46a118634a7f8e67d6f8753d1512/9c1520bc-a5dd-411e-aa04-b6e138fb8897", "gs://test-hieu/tmp/BigQueryWriteTemp/2fec46a118634a7f8e67d6f8753d1512/9573f1d0-1742-4e04-8a2c-cbf9cd9f990e", "gs://test-hieu/tmp/BigQueryWriteTemp/2fec46a118634a7f8e67d6f8753d1512/40a5b885-be18-4de5-8b1a-18cd4a7e2705", "gs://test-hieu/tmp/BigQueryWriteTemp/2fec46a118634a7f8e67d6f8753d1512/99bf2a23-b82d-444a-b286-2e9667b4e180" ],
      "writeDisposition" : "WRITE_TRUNCATE"
    }
  },
  "etag" : "\"8-EGZnPk12W9PiVn0ZRpZVdMBYs/RYObXstf1bVDNaEj4k7hDizD8UQ\"",
  "id" : "momovn-test:2fec46a118634a7f8e67d6f8753d1512_28f0784b6adf4a72e2a27dc45e17b5a9_00001_00000-2",
  "jobReference" : {
    "jobId" : "2fec46a118634a7f8e67d6f8753d1512_28f0784b6adf4a72e2a27dc45e17b5a9_00001_00000-2",
    "projectId" : "momovn-test"
  },
  "kind" : "bigquery#job",
  "selfLink" : "https://www.googleapis.com/bigquery/v2/projects/momovn-test/jobs/2fec46a118634a7f8e67d6f8753d1512_28f0784b6adf4a72e2a27dc45e17b5a9_00001_00000-2",
  "statistics" : {
    "creationTime" : "1525747335309",
    "endTime" : "1525747335436",
    "startTime" : "1525747335436"
  },
  "status" : {
    "errorResult" : {
      "message" : "Not found: Dataset momovn-test:thaodo. Please verify that the dataset exists and the correct location was used for the job.",
      "reason" : "notFound"
    },
    "errors" : [ {
      "message" : "Not found: Dataset momovn-test:thaodo. Please verify that the dataset exists and the correct location was used for the job.",
      "reason" : "notFound"
    } ],
    "state" : "DONE"
  },
  "user_email" : "etl-bigquery@momovn-test.iam.gserviceaccount.com"
}.
	at org.apache.beam.sdk.io.gcp.bigquery.WriteTables.load(WriteTables.java:289)
	at org.apache.beam.sdk.io.gcp.bigquery.WriteTables.access$600(WriteTables.java:79)
	at org.apache.beam.sdk.io.gcp.bigquery.WriteTables$WriteTablesDoFn.processElement(WriteTables.java:158)
ERROR: Non-zero return code '1' from command: Process exited with status 1.
