### ISSUE TITLE
Listing directories with GcsUtil

### ISSUE THREAD

**Issue by zbjornson** [GoogleCloudPlatform/DataflowJavaSDK#66]
I need to get a list of directories in GCS. `GcsUtil.expand` skips directories

https://github.com/GoogleCloudPlatform/DataflowJavaSDK/blob/master/sdk/src/main/java/com/google/cloud/dataflow/sdk/util/GcsUtil.java#L187

Is there a current solution for listing directories?

If not, I'm happy to make a PR, but I don't know how you'd want it designed -- (a) a Boolean argument for `expand` called something like `omitDirectories`, (b) a new method `expandDirectories`, (c) remove the directory skip check but leave everything else unchanged [which will probably break other users' workflows].

**Comment by zbjornson** [comment]
Current workaround, which will miss empty middle-level directories:

	List<GcsPath> filesToProcess = gcsUtil
			.expand(GcsPath.fromUri("gs://<...>/*/*"));
			
	HashSet<GcsPath> directories = new HashSet<GcsPath>();
	for (GcsPath path : filesToProcess) {
		directories.add(path.getParent());
	}
			
	for (GcsPath path : directories) {
		System.out.println(path.toAbsolutePath());
	}

**Comment by dhalperi** [comment]
Can you say more about what you're actually trying to do? Note that in GCS, the notion of a "subdirectory" is really a [convenient "illusion"](https://cloud.google.com/storage/docs/gsutil/addlhelp/HowSubdirectoriesWork).

**Comment by zbjornson** [comment]
I'm doing batch processing of files in directories: one top-level directory becomes a PCollection, and each second-level directory becomes an element in the PCollection. This is a research computing environment where our users upload their files to GCS directly (or it's done automatically from instrument-connected computers), making use of directories (illusions or not) for organization.

**Comment by davorbonaci** [comment]
Hi Zach,
We treat `GcsUtil` as an internal utility of the Dataflow SDK, not a public API for accessing GCS. We don't aim to provide all possible GCS primitives there.

Please keep in mind that listing contents of a GCS bucket is *eventually consistent*, which may make it somewhat harder to depend on the listing output.

You should be able to use your current workaround going forward. Alternatively, you can access the GCS API directly. For example, see [Objects: list](https://cloud.google.com/storage/docs/json_api/v1/objects/list).
