### ISSUE TITLE
Add utility function for creating temp files, clarify docs

### ISSUE THREAD

**Issue by zbjornson** [GoogleCloudPlatform/DataflowJavaSDK#67]
I found out the hard way that `/tmp` is not mounted in the docker containers. (http://stackoverflow.com/questions/33052578/temp-files-in-google-cloud-dataflow) Would be great if a utility class provided methods like `File.createTempFile` and `Files.createTempDirectory` that return a usable location. This would also be good to document on cloud.google.com/dataflow (let me know if I missed this somewhere).

Happy to make a PR if the maintainers provide some input on where the files should be. It seems a bit unusual to save them in a logs directory per the SO answer.

**Comment by davorbonaci** [comment]
Hi Zach,
We should make sure the built-in `File.createTempFile` and `Files.createTempDirectory` works. We should *not* be adding a new utility APIs for this purpose.

Instead, it seems like `java.io.tmpdir` property is controlling the behavior of the standard Java API. We should make sure that it is automatically set to a location that is writable from the user-written code.

Please note that the temporary files may not persist beyond the bundle, which created it. Likewise, bundles may be executing concurrently on a single machine. Hence, access to such files may need to be synchronized.

We'll investigate this and get back to you with more information.

**Comment by zbjornson** [comment]
Thanks David. I still owe Jeremy Lewi a reply to his answer on the SO post I linked above. I haven't had time to investigate further.

(For context, my use case is that I'm running an executable on a bunch of files downloaded via gsutil from GCS, then saving the resulting files back to GCS. Persistence is not a concern.)

**Comment by davorbonaci** [comment]
Experimentally, both `File.createTempFile` and `File.createTempDirectory ` seem to work. We were able to call both methods, write to the file, and read back from it.

Did you actually observe a problem with these APIs?

**Comment by davorbonaci** [comment]
We believe this works correctly. Please reopen if you have any issues!
