### ISSUE TITLE
Regarding CheckStyle-Voilation

### ISSUE THREAD

**Issue by sshubhe** [GoogleCloudPlatform/DataflowJavaSDK#7]
Hi,

I installed apache-mvn-3.1.1,added into my classpath,cloned the GCDSDK and than I ran the command "mvn clean install" but it results in checkstyle-voilations...

Please suggest.

Regards,
Shubh

![image](https://cloud.githubusercontent.com/assets/8649785/6115020/80aeeb10-b070-11e4-90f2-e1147be36c1f.png)

**Comment by davorbonaci** [comment]
Hi Shubh,
Thanks for reporting this.

Checkstyle plugin is complaining that each source file does not end with a newline.

You are running Maven on Windows, which has different newline symbols than our configured defaults. Normally, your Git client is supposed to handle this transparently. You may want to try running `git config core.autocrlf` and experimenting with different options.

If this doesn't help, please reply back and we'll investigate in detail.

Thanks!

**Comment by sshubhe** [comment]
I used all the possible configuration of git config core.autocrlf "true" , "false" and "input" .My build is still showing failure

I am using git 1.9.5

Please suggest.

**Comment by davorbonaci** [comment]
We have committed a change that specifies repository-wide settings regarding newline behavior in Git. These repository-wide settings should override any relevant settings in your client. Just create a fresh clone of the repository for changes to take effect.

I think this should resolve any issues in this space. Please reply back if you are still having issues.

Thanks!
