### ISSUE TITLE
Add support for per-window filenames in AvroIO.Write

### ISSUE THREAD

**Issue by j-mueller** [GoogleCloudPlatform/DataflowJavaSDK#70]
It would be good to be able to set the file names hat AvroIO writes to as a function of the current window, as is already possible for BigQueryIO (https://github.com/GoogleCloudPlatform/DataflowJavaSDK/commit/ccad188c19f0e237c6f9cc126cb553d383ad0be6).

**Comment by davorbonaci** [comment]
Hi Jann,
This is a good idea. This is something we plan to work on soon. Let's keep this issue open to post any relevant updates.

Thanks!

**Comment by dhalperi** [comment]
This is now being tracked for Apache Beam (incubating) as [BEAM-92](https://issues.apache.org/jira/browse/BEAM-92)
