### ISSUE TITLE
NullPointerException in StreamingModeExecutionContext

### ISSUE THREAD

**Issue by bberak** [GoogleCloudPlatform/DataflowJavaSDK#80]
Hi there,

I've go a streaming pipeline (DataflowPipelineRunner) that polls an HTTP endpoint, performs some manipulation and stores the results in a BigQuery table. Based on some rudimentary logging I can see the data is coming down the pipeline. It then encounters the following exception:

```
(b359ca736e4f8d93): Exception: java.lang.NullPointerException
 com.google.cloud.dataflow.sdk.runners.worker.StreamingModeExecutionContext.flushState(StreamingModeExecutionContext.java:246)
 com.google.cloud.dataflow.sdk.runners.worker.StreamingDataflowWorker.process(StreamingDataflowWorker.java:541)
 com.google.cloud.dataflow.sdk.runners.worker.StreamingDataflowWorker.access$300(StreamingDataflowWorker.java:83)
 com.google.cloud.dataflow.sdk.runners.worker.StreamingDataflowWorker$5.run(StreamingDataflowWorker.java:435) java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
 java.lang.Thread.run(Thread.java:745)
```

I'm using version 1.2.0 of the Dataflow Java SDK.

Any help would be greatly appreciated, please let me know if I can provide more details.

**Comment by bberak** [comment]
To others who experience the same issue, don't forget to override the getWatermark method of any custom UnboundedReaders you have coded (don't return null).

**Comment by davorbonaci** [comment]
Thanks Boris!

Indeed, `getWatermark` should return a lower bound *estimate* on timestamps of future elements read by a reader, and never a `null`.
