### ISSUE TITLE
Ability to specify name for MapElements.via transforms

### ISSUE THREAD

**Issue by zbjornson** [GoogleCloudPlatform/DataflowJavaSDK#84]
I've got a pipeline comprised entirely of a series of `.apply(MapElements.via(new SimpleFunctionX))`s. Would be nice to be able to set the name property so this can be [monitored](https://cloud.google.com/dataflow/pipelines/dataflow-monitoring-intf) with nicer names than "MapElements1," "MapElements2," ... maybe `MapElements.via(sf).named("name")`?

**Comment by bjchambers** [comment]
You can use `.apply("name", MapElements.via(sf))` to provide a name for any transform.

**Comment by zbjornson** [comment]
Sweet! Thanks. Probably good to document that on the [monitoring page](https://cloud.google.com/dataflow/pipelines/dataflow-monitoring-intf)...
