### ISSUE TITLE
BigQueryTableRowIterator should allow non-default location for temporary data set

### ISSUE THREAD

**Issue by nevillelyh** [GoogleCloudPlatform/DataflowJavaSDK#86]
It seems that a query request may fail if the destination dataset is not in the same region as original table being queried.
Newly created datasets are in "US" by default and will fail if table being queried is in "EU".

**Comment by dhalperi** [comment]
Hi Neville,

Thanks for reporting this. We're working on a fix.

**Comment by dhalperi** [comment]
BigQuery now will tell you what `location` a query will run in when you `dry_run` it. We now use this information to set the `location` for the temporary dataset -- so this issue should be fixed without any API changes.

Thanks!
Dan

**Comment by nevillelyh** [comment]
Just curious how do you get this information with the BQ Java client?
I'm using `google-api-services-bigquery:v2-rev275-1.21.0` and don't see a location field in the dry run job response.

**Comment by dhalperi** [comment]
@nevillelyh - right now I believe the field is only populated when you dry run an `insert` job.
