### ISSUE TITLE
Suspending an UnboundedReader for an interval of time

### ISSUE THREAD

**Issue by bberak** [GoogleCloudPlatform/DataflowJavaSDK#87]
Hi there,

I've written a custom UnboundedReader, which after retrieving some data from a remote endpoint, can be laid to rest for about 20 minutes or so. I'm a bit sketchy about the behaviour of my UnboundedReader if I return false from the "advance" method and was hoping I could get some advice.

If my UnboundedReader does return false from the "advance" method - will it get called at a later time? How much later? How often? Is this something I can control? My idea would be to record the instant I no longer wish to fetch the remote data, and then check if 20 minutes have passed each subsequent time the "advance" method is called - does that seem like a reasonable workflow?

I really appreciate any ideas/help I can get - cheers.

**Comment by dhalperi** [comment]
Hi Boris,

This should work exactly as you described it. 

If you return `false` from `UnboundedReader.advance`, this simply means that ["there is no more input data *currently* available"](https://github.com/GoogleCloudPlatform/DataflowJavaSDK/blob/0c637d38a89eecf7d31bee913f00e1c89365e379/sdk/src/main/java/com/google/cloud/dataflow/sdk/io/UnboundedSource.java#L45). You can also see there that "future calls to `advance` may return `true` once more data is available."

(It looks like the key word *currently* is missing in the Javadoc for `advance`, but present in `start`. I'll submit a fix.)

Please let us know if there are issues or if you have followup questions.

Thanks,
Dan

**Comment by bberak** [comment]
Thanks for the response Daniel.

I couldn't find any documentation regarding this: I'm just wondering how long I can expect to wait for a subsequent call to `UnboundedReader.advance` after returning `false`. Is it like minutes, hours etc or something arbitrary?

Cheers.

**Comment by dhalperi** [comment]
Unless the system is overloaded, the next call to `UnboundedReader.advance` will typically come within a second. When the pipeline is not overwhelmed, you should not expect to see hours, minutes or even tens of seconds.

**Comment by bberak** [comment]
Thanks Daniel, appreciate the help.
