### ISSUE TITLE
manage multiple pipeline from one dataflow job

### ISSUE THREAD

**Issue by albertog** [GoogleCloudPlatform/DataflowJavaSDK#88]
Can you provide me  example of how can I manage multiple pipelines in one dataflow job. Invoking one or other depending of my parameters. Or a least one link with a similar matter. 

I have googling but no I have not find it.

**Comment by dhalperi** [comment]
Hi Alberto,

Does this link help? In this program, we're choosing between streaming and batch (and using different sources and sinks as a result) based on pipeline options.

If not, please explain more about what you're looking for -- I'm not quite sure from the question.

Thanks,
Dan

**Comment by dhalperi** [comment]
https://github.com/GoogleCloudPlatform/DataflowJavaSDK/blob/master/examples/src/main/java/com/google/cloud/dataflow/examples/complete/TrafficRoutes.java#L358

**Comment by dhalperi** [comment]
Hi Alberto,

I'm closing this issue since it's been a month. Please comment or file a new issue if you are still having trouble.

Thanks!
Dan
