### ISSUE TITLE
Breaching the max number of worker instances

### ISSUE THREAD

**Issue by bberak** [GoogleCloudPlatform/DataflowJavaSDK#92]
Hi there,

I've created a streaming job in which I have set the max number of worker instances to 1 (via the DataflowPipelineOptions class).

However, when the job begins running - I can see it is using 3 compute engine instances instead of 1. The reserved CPU time for my Dataflow jobs also seems to reflect this (as well as my monthly charges).

I have been able to successfully set the worker machine type however - just not the number of instances. Also, I have not turned on auto-scaling (and I don't think this feature is available for streaming jobs in any case).

Any help would be greatly appreciated. Cheers!

**Comment by dhalperi** [comment]
Hi Boris,

Can you confirm which options you're setting exactly?

If you are setting `--maxNumWorkers=1` but not `--numWorkers`, can you please see if also setting `--numWorkers=1` makes the behavior as intended?

Thanks!

**Comment by bberak** [comment]
Thanks for your help Daniel.

After explicitly setting the ```maxNumWorkers``` and ```numWorkers``` properties to 1, I can now see that my job is only using a single compute instance.

For the benefit of others, I'm not actually using the command line options but explicitly calling the following methods from code (I infer that the following is the same as using the command line flags):

```
DataflowPipelineOptions options = PipelineOptionsFactory.create().as(DataflowPipelineOptions.class);
options.setRunner(DataflowPipelineRunner.class);
options.setProject("project-name");
options.setMaxNumWorkers(1);
options.setNumWorkers(1);
...
```

**Comment by dhalperi** [comment]
Hi Boris,

As of a Google Cloud Dataflow service upgrade today, `--maxNumWorkers` will be used as an upper bound on the number of workers started even if `--numWorkers` is not set.

So `--maxNumWorkers=1` by itself should be enough to force the job to use 1 worker.

Thanks for reporting this issue!

**Comment by bberak** [comment]
No worries Daniel, cheers for the update!
