### ISSUE TITLE
What PipelineRunners (Google Cloud, Direct, Apache, etc.) support Dataflow?

### ISSUE THREAD

**Issue by fsalem** [GoogleCloudPlatform/DataflowJavaSDK#93]
I was trying to create a custom Source but after implementing each needed class, I got this exception
"no evaluator registered for UnboundedSource [Read(UnboundedSource)]"

**Comment by fsalem** [comment]
You can find the demo project on https://github.com/fsalem/dataflow-kafka-demo

**Comment by dhalperi** [comment]
Ahh. Are you trying to use the DirectPipelineRunner? Indeed, that runner does not directly support UnboundedSource.

Instead, you can turn the `UnboundedSource` into a `BoundedSource` for testing using [`withMaxNumRecords`](https://github.com/GoogleCloudPlatform/DataflowJavaSDK/blob/master/sdk/src/main/java/com/google/cloud/dataflow/sdk/io/Read.java#L190):

```java
UnboundedSource<String> unboundedSource  = ...; // make a Kafka source
PCollection<String> boundedKafkaCollection =
    p.apply(Read.from(unboundedSource).withMaxNumRecords(10));
```

**Comment by fsalem** [comment]
Thanks so much. I got it, but which pipelinerRunner should I use If I want to run it on my own cluster ? not Google cluster. When I tried to use DataflowPipelineRunner, I found that I have to set some params such as project Id and credentials.

**Comment by fsalem** [comment]
@dhalperi  Your reply is really helpful :)

**Comment by dhalperi** [comment]
Dataflow provides several runners in the SDK itself, and there are several community contributed runners that are maintained in separate repositories.

`DirectPipelineRunner` executes pipelines on the local machine. It adds a lot of verification to your pipeline to ensure it adheres to the Dataflow programming model -- its emphasis is on testing, not performant execution. At this time, this runner can run over bounded `PCollection`s only. We are actively working on removing this restriction. In the meanwhile, an unbounded `PCollection` can be trivially converted into a bounded one by using the code snippet posted above.

`[Blocking]DataflowPipelineRunner` executes pipelines in Google Cloud Platform. We encourage you to give Google Cloud a [free trial](https://cloud.google.com/free-trial/): you get $300 credit to spend over 60 days to determine whether it will work for you.

In partnership with Cloudera, you can run Dataflow pipelines on an [Apache Spark](http://spark.apache.org) cluster using the [`SparkPipelineRunner`](https://github.com/cloudera/spark-dataflow). Additionally, you can run Dataflow pipelines on an [Apache Flink](http://flink.apache.org/) cluster using the [`FlinkPipelineRunner`](https://github.com/dataArtisans/flink-dataflow).

Both of these runners support bounded PCollections only  -- support for unbounded ones is in the works for these community-contributed runners. See [this pull request](https://github.com/cloudera/spark-dataflow/pull/76) for candidate streaming support for the Spark runner.

Hope this helps!

**Comment by fsalem** [comment]
@dhalperi Thanks so much :)

**Comment by orian** [comment]
BTW $300 works only in some parts of the world (e.g. doesn't work in EU for non-companies)
