### ISSUE TITLE
Game Example Column Mislabeled

### ISSUE THREAD

**Issue by absolutelyNoWarranty** [GoogleCloudPlatform/DataflowJavaSDK#95]
The HourlyTeamScore example is writing the team name to the BigQuery table but gives it the [column name "user"](https://github.com/GoogleCloudPlatform/DataflowJavaSDK/blob/2fc26c5d41d01ff476f293d388cc308f47ea7c7f/examples/src/main/java8/com/google/cloud/dataflow/examples/complete/game/HourlyTeamScore.java#L127).

**Comment by amygdala** [comment]
Thank you for the catch!  We'll fix that shortly.  In the meantime, you can change the string from "user" to "team" to get the correct column name.

**Comment by dhalperi** [comment]
Fixed by e9bb2a2794fc31a9aa456465616b5e8fd06b8f6b.

The change is live on GitHub now, and will appear in the next Dataflow SDK release.

Thanks again for reporting!
