### ISSUE TITLE
PipelineRunner for AWS services?

### ISSUE THREAD

**Issue by cmenguy** [GoogleCloudPlatform/DataflowJavaSDK#99]
Hi there, I was wondering if there is any plan to have a `PipelineRunner` for AWS services like AWS Data Pipeline? Are contributions in that sense welcome, or is it intended to stay in GCP for now?
I think it would be pretty cool and help drive adoption as well as position the project as more vendor-neutral which would make sense if it's accepted as an Apache project.

I'm still learning my way through DataFlow but it seems like the batch use case would be possible to run on AWS Data Pipeline, right? For the realtime use case potentially by having very small schedule interval, although I'm not too sure how it would look in practice.

**Comment by davorbonaci** [comment]
Hi Charles,
We don't have any plans for a runner for any AWS-specific service at this time. I'm not aware of any specific effort in this space. (That said, one might deploy a Spark / Flink cluster in AWS today and use those runners to execute a Dataflow pipeline in AWS.)

In general, we welcome all types of runners. As part of our [Apache Incubator proposal](http://googlecloudplatform.blogspot.com/2016/01/Dataflow-and-open-source-proposal-to-join-the-Apache-Incubator.html), we specifically call out *portability*. The idea is that pipelines are portable across a number of runtime engines, and users can choose a runtime based on any number of considerations, such as performance, cost, or scalability.

You also touched on a technical feasibility. I cannot comment on the specifics for AWS Data Pipeline, but I can concur that the batch use case is often much easier than the streaming one. On our side, however, we are investigating a significant refactoring that would solidify the interface to runners. If you are looking to start an effort to write a runner, I might suggest to wait until this refactoring is complete. Of course, any exploratory and prototyping steps can be done right now.

Thanks,
Davor
